---
title: Space Jam
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Minimal storytellers
url: https://ajirogo.com
author:
  name: Pratig Ajirogo
  url: https://ajirogo.com
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
permalink: "/:year-:month-:day/:title"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- tale.gemspec
